# This is a basic workflow to help you get started with Actions

name: Publish2vscode

on:
  release:
    types:
      - created

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: yarn

      # Runs a single command using the runners shell
      - name: Package the extension
        run: yarn package

      - name: Publish
        run: yarn deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
